# Project information
site_name: Intro into AI and LLM Workshop
site_url: https://ibm.github.io/intro-ai-llm-workshop/
site_author: IBM Research

# Repository
repo_name: intro-ai-llm-workshop
repo_url: https://github.com/IBM/intro-ai-llm-workshop
edit_uri: edit/main/docs

# Navigation
nav:
  - Welcome:
    - About the workshop: README.md
  - Workshop:
    - Lab 0. Pre-work: pre-work/README.md
    - Lab 1. Command-Line Ollama: lab-1/README.md
    - Lab 2. Using Open-WebUI Interface: lab-2/README.md
    - Lab 3. Graphics and MultiModal LLM: lab-3/README.md
    - Lab 4. Retrieval-Augmented Generation: lab-4/README.md
    - Lab 5. Agentic AI with Open-WebUI: lab-5/README.md
  - References:
    - Additional Resources: resources/RESOURCES.md
    - Contributors: resources/CONTRIBUTORS.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2025 IBM Research

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - navigation.footer
    #- navigation.instant
    - content.code.copy
    - content.tabs.link
  palette:
    scheme: default
    primary: blue
    accent: blue

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
